"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _chat_list from './chat-list.bones.json'
import _profile_page from './profile-page.bones.json'

registerBones({
  "chat-list": _chat_list,
  "profile-page": _profile_page,
})
